### ISSUE TITLE
TODO: GATEWAY COMMANDS & EVENTS

### ISSUE THREAD

**Issue by AkiaCode** [discord-deno/discord.deno#9]
## GATEWAY COMMANDS
- [x] Identify 
- [x] Resume 
- [x] Heartbeat 
- [x] Request Guild Members 
- [x] Update Voice State
- [x] Update Status

## GATEWAY EVAENTS
- [x] Hello
- [x] Ready 
- [x] Resumed
- [x] Reconnect
- [x] Invalid Session
- [x] Channel Create
- [x] Channel Update 
- [x] Channel Delete 
- [x] Channel Pins Update
- [x] Guild Create
- [x] Guild Update
- [x] Guild Delete 
- [x] Guild Ban Add 
- [x] Guild Ban Remove 
- [x] Guild Emojis Update
- [x] Guild Integrations Update 
- [x] Guild Member Add
- [x] Guild Member Remove
- [x] Guild Member Update
- [x] Guild Members Chunk 
- [x] Guild Role Create
- [x] Guild Role Update 
- [x] Guild Role Delete 
- [x] Invite Create
- [x] Invite Delete 
- [x] Message Create
- [x] Message Update 
- [x] Message Delete 
- [x] Message Delete Bulk
- [x] Message Reaction Add
- [x] Message Reaction Remove 
- [x] Message Reaction Remove All
- [x] Message Reaction Remove Emoji
- [x] Presence Update 
- [x] Typing Start 
- [x] User Update
- [x] Voice State Update 
- [x] Voice Server Update
- [x] Webhooks Update

## Reference
https://discord.com/developers/docs/topics/gateway#commands-and-events-gateway-events

**Comment by minseo0388** [comment]
철자는 넘어가자

**Comment by AkiaCode** [comment]
Done.
